- name: My first play
  hosts: myhosts
  become: true
  tasks:
    
    - name: Import RPM Fusion keys
      ansible.builtin.rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

    - name: Import RPM Fusion nonfree keys
      ansible.builtin.rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

    - name: Add RPM Fusion Free repository
      ansible.builtin.dnf:
        name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
        state: present

    - name: Add RPM Fusion Non-Free repository
      ansible.builtin.dnf:
        name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
        state: present

    - name: Ensure the RPM Fusion repositories are enabled
      ansible.builtin.dnf:
        name:
          - rpmfusion-free-release
          - rpmfusion-nonfree-release
        state: present

    - name: Ensure vlc installed
      ansible.builtin.dnf:
        name: vlc
        state: present

    - name: Remove ffmpeg-free
      ansible.builtin.dnf:
        name: ffmpeg-free
        state: absent
      become: true
      tags: 
        - ffmpeg
    
    - name: Install ffmpeg
      ansible.builtin.dnf:
        name: ffmpeg
        state: present
        allowerasing: true
      become: true
      tags: 
        - ffmpeg

    - name: Install xrandr
      ansible.builtin.dnf:
        name: xrandr
        state: present


